version: '3'

services:
    web_app:
        build: 
          context: D:\IUT\IUT_Semestre_2\SAE23\CopieSite\docker
        container_name: debianTom
        tty: true
        stdin_open: true
        depends_on:
            - db_app
        ports:
            - "80:80"
        networks:
            - net-app
    db_app:
        image: mariadb
        container_name: mariadbTom
        environment:
            - MYSQL_ROOT_PASSWORD=
            - MYSQL_DATABASE=malossesae23
        ports:
            - "3306:3306"
        networks:
            - net-app
networks:
  net-app:
    name: net-app
volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
